# Generated by Django 3.2.4 on 2021-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_pic',
            field=models.ImageField(default='1.png', upload_to='ids'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='1.png', upload_to='profile_pics'),
        ),
    ]
