# Generated by Django 3.2.4 on 2021-06-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0002_auto_20210621_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_pic',
            field=models.ImageField(upload_to='ids'),
        ),
    ]
