# Generated by Django 3.2.4 on 2021-06-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0006_complaint_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='action',
            field=models.IntegerField(choices=[(1, 'Resistered'), (2, 'Received'), (3, 'Pending For Enquirey'), (4, 'Investigation'), (5, 'Action Taken'), (6, 'Closed')], default=1),
        ),
    ]
