# Generated by Django 3.2.4 on 2021-06-25 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0007_complaint_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='action',
        ),
        migrations.CreateModel(
            name='complaintstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'Resistered'), (2, 'Received'), (3, 'Pending For Enquirey'), (4, 'Investigation'), (5, 'Action Taken'), (6, 'Closed')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeapp.complaint')),
            ],
        ),
    ]
