# Generated by Django 3.2.4 on 2021-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0008_auto_20210625_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintstat',
            name='assigned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaintstat',
            name='statdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
