# Generated by Django 3.2.4 on 2021-06-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0009_auto_20210625_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('firid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('signedby', models.CharField(max_length=20)),
                ('content', models.TextField(default='First Information Report not yet submitted')),
            ],
        ),
    ]
