# Generated by Django 3.2.4 on 2021-06-27 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0011_fir_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='Crime_No',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='fir',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
